---
title: "Figure 7C"
output: html_document
author: Qingsong Cai from the University of Texas MD Anderson Cancer Center
date: '2025-01-07'
---

## The following code repoduces the figure 7C in DTP cell manuscripts by Qingsong Cai.
```{r,warning=FALSE, message=FALSE}
library(factoextra)
library(RColorBrewer)
```

```{r}
main_dir <- ("../../processed_data/RNAseq_MCL_samples_147_578_3838_278a/")
```

```{r,warning=FALSE, message=FALSE}
#load("20230803.for.coxph.rdata") 
load(paste0(main_dir,"Data/N20230911.for.coxph.rdata"))  #get pcDat5, pathways.all, info.t, normalizedCounts, countdata.t
     #\\\\d1prprsh3ccifs/home/lym_myl_rsch/MCL_Lab/Qingsong/007analysis/RNAseq"
info.t$Therapy_Status <- info.t$current_therapy_status
#info.t[info.t$Therapy_Status %in% "Non-response", ]
#info.t[info.t$Therapy_Status %in% "Response", ]
#info.t[info.t$current_therapy_status %in% "non_Response", ]$Therapy_Status <- "Non-response"

info.t$Therapy_Status <-factor(info.t$Therapy_Status, levels = c("Non-response",
                                                                 "Response",
                                                                 "Nondetermined", 
                                                                 "Margin" ))
info.t$Groups <- info.t$Therapy_Status
```

#Fig 7C
```{r, warning=FALSE, message=FALSE, fig.width = 8, fig.height = 8}
fig7C <- fviz_pca_ind(pcDat5,habillage=info.t$Group, geom="point",  pointsize = 4,
                      palette = c( "#efc000", c(brewer.pal(n = 4, name = "Blues"))[4], "gray1", "grey2")) + 
    theme(legend.position = c(0.2,0.8)) + scale_shape_manual(values=c(15,16,3,4))
fig7C
```
